#!/bin/sh
mkdir "/data/user-files/Audio Loops"
mkdir "/data/user-files/Aida DSP Models"
mkdir "/data/user-files/Audio Loops"
mkdir "/data/user-files/Audio Recordings"
mkdir "/data/user-files/Audio Samples"
mkdir "/data/user-files/Audio Tracks"
mkdir "/data/user-files/MIDI Clips"
mkdir "/data/user-files/MIDI Songs"
mkdir "/data/user-files/NAM Models"
mkdir "/data/user-files/Reverb IRs"
mkdir "/data/user-files/SF2 Instruments"
mkdir "/data/user-files/SFZ Instruments"
mkdir "/data/user-files/Speaker Cabinets IRs"

